repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
            args: [ --markdown-linebreak-ext=md ]
  -   repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      # Ruff added before Black as autofix is enabled
      rev: v0.0.292
      hooks:
        -   id: ruff
            args: [ --fix, --exit-non-zero-on-fix ]
  -   repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
        -   id: black
            # It is recommended to specify the latest version of Python
            # supported by your project here, or alternatively use
            # pre-commit's default_language_version, see
            # https://pre-commit.com/#top_level-default_language_version
            language_version: python3.11
            args: ["--line-length", "79"]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.5.1'  # Use the sha / tag you want to point at
      hooks:
        -   id: mypy
  -   repo: https://github.com/regebro/pyroma
      rev: '4.2'
      hooks:
        -   id: pyroma
